### ISSUE TITLE
seqFF.R script not working

### ISSUE THREAD

**Issue by smruti241** [seqinfo/FF#1]
I am using your FF script for fetal fraction. The last code is not working due to seqFF.R script. It is showing me error and error. It would be good if you updated this script as well as attach the seqFF.R script so that I can know which script did you use. Please help me regarding this.

**Comment by PriitPaluoja** [comment]
Hi! You can find the SeqFF script itself in the original publication under the supplementary info:

- PMID: 25967380
- DOI: 10.1002/pd.4615 

Changes made to the original script to support scripts in this repository can be found from the Master's thesis available [here](https://comserv.cs.ut.ee/home/files/paluoja_computer_science_2019.pdf?study=ATILoputoo&reference=D311616C76871BA93389C99B5001DEBE814F1A16).

**Comment by smruti241** [comment]
But where is the link for downloading seqFF script? I found only the algorithmic and principle part. I need seqFF.sam.R script which you have mentioned in this given script

**Comment by smruti241** [comment]
I am using the same script but it is giving some errors, I need to know how did you use that script? Did you change any parameters?

**Comment by PriitPaluoja** [comment]
Did you consult the referenced Master's thesis in my previous response? In the thesis, all the instructions are provided. This repository is created to supplement the Master's thesis.

**Comment by smruti241** [comment]
Yeah I have gone through it. But i didnt find the script requirements. Thats why i am asking

**Comment by PriitPaluoja** [comment]
From the page 26 please find the following:

_The source code was adapted to accept input from Linux pipe and to return a value that would allow to use the whole script as a tool in the pipeline._

**Comment by smruti241** [comment]
Ok I will look into it and get back to you. Thanks!

**Comment by smruti241** [comment]
hii @PriitPaluoja I ran that seqFF script, I was running step-by-step actually, I ran this code:
##### READ IN DATA
if( datatype == "sam" )
{
dat <- read.table(pipe(paste("cut -f3,4",file("S_57_IonXpress_001.sam"),sep=" ")), header=FALSE,colClasses= c("character","integer"))
colnames(dat)=c("refChr","begin")


dat=dat[dat$refChr!="*" & dat$refChr!="chrM" ,]
binindex = ifelse((dat$begin%%50000)==0,floor(dat$begin/50000)-1,floor(dat$begin/50000))

fastbincount = table(paste(dat$refChr,binindex, sep="_"))
newtemp=as.data.frame(matrix(NA, ncol=2, nrow=length(fastbincount)))
newtemp[,1]=paste(names(fastbincount))
newtemp[,2]=as.numeric(paste(fastbincount))
colnames(newtemp)=c("binName","counts")

}
if( datatype =="counts" )
{
newtemp <- read.table(file.name, header=FALSE,colClasses= c("character","integer"))
colnames(newtemp)=c("binName","counts")
}

bininfo = merge(bininfo, newtemp, by="binName",all.x=T)
bininfo=bininfo[order(bininfo$binorder),]

but it is giving me error:
Error in if (datatype == "sam") { : missing value where TRUE/FALSE needed
Error in if (datatype == "counts") { : 
  missing value where TRUE/FALSE needed

What shall I add to this code?

**Comment by PriitPaluoja** [comment]
Around line 23 please modify correspondingly: dat <- read.table(**file("stdin")**, header=FALSE,colClasses= c("character","integer"))

End of the script add the following:

- temp_ff=c((wrsc+enet)/2, enet, wrsc)
- names(temp_ff)=c("SeqFF","Enet","WRSC")
- temp_ff <- t(data.frame(temp_ff))
- write(paste(temp_ff[1],temp_ff[2],temp_ff[3],sep = "\t"), stdout())

**Comment by smruti241** [comment]
Ok let me see if it works

**Comment by smruti241** [comment]
same error: Error in if (datatype == "sam") { : missing value where TRUE/FALSE needed
Execution halted

**Comment by PriitPaluoja** [comment]
Please try removing the if/else check.

If you wish to find fetal fractions with SeqFF, I recommend following SeqFF author's publication (PMID: 25967380) instructions and constructing the pipeline according to their manual.

**Comment by smruti241** [comment]
yeah I want to know fetal fractions. I read your thesis and got to know that you used DEFRAG also. Can you help me in that?

**Comment by smruti241** [comment]
But you can help me in this script. Your code is also for fetal fraction, right?

**Comment by PriitPaluoja** [comment]
I did not apply DEFRAG, it was only in the literature overview. 

If your end-goal is to find fetal fractions, then I really recommend constructing a pipeline from scratch and closely following SeqFF publication. You can reference the `.sh` file used in here, but it is not optimal and you might want to change parameters. Also, it is relevant to consider the use of some Workflow Management System (Cromwell, Nextflow etc) if you plan to analyse more than a few samples. May I ask if you are building it for scienetific purpose of production use?

**Comment by smruti241** [comment]
Actually I am designing a pipeline for NIPT analysis. Si I want to use seqFF and DEFRAG for fetal fraction and gender identification. I considered PREFACE but for that, I need config file in which there should be data available about gender and fetal fraction. So, I want to use these both tools

**Comment by smruti241** [comment]
I am facing issue while running DEFRAG script. I hope you know python, so it would be very kind of you if you help me. For seqFF, I will try to fix it.

**Comment by PriitPaluoja** [comment]
May I ask, from which institution are you from?  Would you be interested in the licencing of the working NIPT protocol?

**Comment by smruti241** [comment]
I am from a diagnostic company in India. Right now, I have started working on it.

**Comment by smruti241** [comment]
@PriitPaluoja do you know python? can you help me please?
